[package]
name = "numa_maps"
version = "0.0.0"
edition = "2021"
authors = ["Moritz Hoffmann <antiguru@gmail.com>"]
description = "Parse the numa_maps file"
license = "MIT OR Apache-2.0"
repository = "https://github.com/antiguru/numa_maps"
rust-version = "1.72"
